name: my first github action

on: push

jobs:
  first_job:
    runs-on: ubuntu-lastest
    steps:
    - name: welcome to my first git action
      run: echo "welcome to my first github project"
    - name: list folder
      run: ls
    - name: read file
      run: cat README.md